name: hotdog_sweep
program: hotdog/cli.py
method: bayes
metric:
  goal: maximize
  name: Validation metrics/val_acc
parameters:
  optimizer:
    values:
      - Adam
      - SGD
  # lr:
  #   values:
  #     - 0.0001
  #     - 0.001
  #     - 0.01
  #     - 0.1
  data_augmentation:
    values:
      - True
      - False
  batchnorm:
    values:
      - True
      - False
  dropout:
    values: 
      - 0
      - 0.25
      - 0.5
      - 0.75